highlighter: pygments
permalink: /:year/:month/:day/:title/
markdown: kramdown
name: "荒芜之地"

author: "darkkate"
atom-baseurl: "darkkate.com"

navigations:
  - title: Archive
    class: fa fa-archive
    href: /archive
  - title: Categories
    class: fa fa-th-list
    href: /categories
  - title: Tags
    class: fa fa-tags
    href: /tags
  - title: About
    class: fa fa-user
    href: /about
  - title: Instagram
    class: fa fa-instagram
    href: https://instagram.com/hidarkkate/
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

