markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
markdown: rdiscount
name: "the same blog"

author: "darkkate"
atom-baseurl: "blog.darkkate.com"

navigations:
  - title: Archive
    class: fa fa-archive
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-instagram
    href: https://instagram.com/hidarkkate/
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

